@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

' ==== Clase base abstracta ====
abstract class Entidad {
- String nombre
- int salud
- int ataque
- Posicion posicion
--
+ abstract void mover( )
+ abstract void atacar(Entidad e)
+ void recibirGolpe(int cantidad)
+ boolean estaVivo( )
}

class Jugador{

--
+ void mover( )
+ void atacar(Enemigo e)
+ void recibirGolpe(int cantidad)
}

class Enemigo {
--
+ void mover( )
+ void atacar(Jugador j)
+ void recibirGolpe(int cantidad)
}

class Posicion {
- int x
- int y
--
+ void setPos(int x, int y)
+ int getX( )
+ int getY( )
}

' ==== Relaciones ====
Jugador --|> Entidad
Enemigo --|> Entidad
Entidad --> Posicion

@enduml