@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class Juego{
- Jugador jugador
- Enemigo[] enemigo
- Mapa mapa
- boolean corriendo
--
+ void iniciar( )
+ void actualizar( )
+ void detener( )
}

class Jugador{
- String nombre
- int salud
- int ataque
- Posicion posicion
--
+ void mover( )
+ void atacar(Enemigo e)
+ void recibirGolpe(int cantidad)
}

class Enemigo{
- String tipo
- int salud
- int ataque
- Posicion posicion
--
+ void mover( )
+ void atacar(Jugador j)
+ void recibirGolpe(int cantidad)
}

class Mapa{
- int ancho
- int alto
- Posicion[ ][ ] coordenadas
--
+ void cargar( )
}

class Posicion{
- int x
- int y
--
+ void setPos(int x, int y)
+ int getX( )
+ int getY( )
}

' ==== Relaciones ====
Juego "1" --> "1" Jugador
Juego "1" --> "*" Enemigo
Juego "1" --> "1" Mapa

Jugador "1" --> "1" Posicion
Enemigo "1" --> "1" Posicion
Mapa "*" --> "*" Posicion

@enduml